/// @file     Global_Header.h
/// @date     2025/02/17
/// @author   Jaejin Ham
/// @brief    Include Program header Files

#ifndef _GLOBAL_HEADER_H_
#define _GLOBAL_HEADER_H_

/*  아래의 코드 중 사용하지 않는 h파일 들은 모두 주석 처리하여 include 시키지 않고 미사용 처리한다  */

// Header files generated by code generator
#include "r_smc_entry.h"


// Data Flash Access Library files
//#include "fdl.h"
//#include "fdl_types.h"
//#include "fdl_descriptor.h"


// EEPROM Emulation Library files
//#include "eel.h"
//#include "eel_types.h"
//#include "eel_user_types.h"
//#include "eel_usersource.h"


// First Include header
#include "Type_Define.h"
#include "User_Config.h"
#include "User_Define.h"
#include "Type_Convert.h"
#include "Water_Temp_Table.h"


// Header files for HW Driver
#include "Hal_AC_Motor.h"
#include "Hal_BLDC_Motor.h"
#include "Hal_BoostPump.h"
#include "Hal_Buzzer.h"
#include "Hal_DC_Fan.h"
#include "Hal_DC_Pump.h"
#include "Hal_Debug.h"
#include "Hal_EEPROM.h"
#include "Hal_EW_Module.h"
#include "Hal_Flowmeter.h"
#include "Hal_GeneralADC.h"
#include "Hal_HumidTempSensor.h"
#include "Hal_LeakSensor.h"
#include "Hal_ReedSW.h"
#include "Hal_RTC_EEPROM_ISL12026.h"
#include "Hal_SmallValve.h"
#include "Hal_Stepmotor.h"
#include "Hal_StirringMotor.h"
#include "Hal_TDS.h"
#include "Hal_UV.h"
#include "Hal_Valve.h"
#include "Hal_Voice_NXD1005.h"
#include "Hal_WaterLevelSensor.h"

/* 미세먼지 센서 관련 */
#include "Hal_DustSensor_PPD71.h"
#include "Hal_DustSensor_Sen54.h"
#include "Hal_DustSensor_PMS5003.h"
#include "Hal_DustSensor_PPD42NS.h"
#include "Hal_DustSensor_PPD4260.h"

/* 히팅 관련 */
#include "Hal_Heater.h"
#include "Hal_InstantaneousHeater.h"
/* 냉각 관련 */
#include "Hal_NormalComp.h"
#include "Hal_BLDC_Comp.h"
#include "Hal_TEM.h"
/* 얼음 관련 */
#include "Hal_AC_Motor_IceMaking.h"
#include "Hal_IceSwingBar.h"
#include "Hal_Input_IceTray.h"
#include "Hal_Motor_GasSwitch.h"
#include "Hal_Motor_IceDoor.h"
#include "Hal_Motor_IceTray.h"


// Header files for Operation
#include "Lib_ADConvert.h"
#include "Lib_Buzzer.h"
#include "Lib_EEPROM.h"
#include "Lib_Memento.h"
#include "Lib_OperationMode.h"
#include "Lib_RTC.h"
#include "Lib_TDS.h"
#include "Lib_TimeScheduler.h"
#include "Lib_Water_BoostPump.h"
#include "Lib_Water_Effluent.h"
#include "Lib_Water_ErrorCheck.h"
#include "Lib_Water_Fan.h"
#include "Lib_Water_LevelSensor.h"
#include "Lib_Water_PowerSave.h"
#include "Lib_Water_PTA_Mode.h"
#include "Lib_Water_Setup.h"
#include "Lib_Water_TankWaterInput.h"
#include "Lib_Water_TestMode.h"
#include "Lib_Water_UV_Sterilize.h"
#include "Lib_Water_Voice.h"
/* 히팅 관련 */
#include "Lib_Water_Heater.h"
#include "Lib_Water_InstantaneousHeater.h"
/* 냉각 관련 */
#include "Lib_Water_Cool_BLDCComp.h"
#include "Lib_Water_Cool_NormalComp.h"
#include "Lib_Water_Cool_TEM.h"
/* 얼음 관련 */
#include "Lib_Water_IceMaking_ModeDecision.h"
#include "Lib_Water_IceMaking.h"
/* 청정기 관련 */
#include "Lib_Air_BLDCMotor.h"
#include "Lib_Air_Filter.h"


// Base header files
#include "Func_ADC.h"
#include "Func_External_Interrput.h"
#include "Func_Uart.h"
#include "Basic_Loop.h"


// Header files for Wifi
#include "WIFI_control.h"


// Header files generated by user
#include "User_EEPROM.h"
#include "User_RTC.h"
#include "User_Main.h"


// library header files
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <math.h>

#endif
